version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: email_scheduler_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: email_scheduler
      POSTGRES_USER: scheduler_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduler_user -d email_scheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: email_scheduler_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  volumes:
    postgres_data:
      driver: local
    pgadmin_data:
      driver: local
